# Generated by Django 2.1.2 on 2018-10-11 02:29

from django.db import migrations
import django_pgtree.fields


class Migration(migrations.Migration):

    dependencies = [("testapp", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="testmodel", options={"ordering": ("tree_path",)}
        ),
        migrations.AlterField(
            model_name="testmodel",
            name="tree_path",
            field=django_pgtree.fields.LtreeField(unique=True),
        ),
    ]
